name: "Lint PR"

on:
  pull_request:
    branches: [ main ]

# This job ensures that prs adhere to conventional commits
jobs:
  main:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - uses: amannn/action-semantic-pull-request@v3.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
